# Generated by Django 3.0.2 on 2020-01-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredApps',
            fields=[
                ('app_id', models.IntegerField(primary_key=True, serialize=False)),
                ('app_activity', models.TextField()),
                ('app_name', models.CharField(max_length=255)),
                ('app_exe', models.CharField(max_length=255)),
                ('app_started', models.DateTimeField()),
            ],
        ),
    ]
